### ISSUE TITLE
[Bug] Clicking the prefix button in a Workspace toggles the repo's dropdown

### ISSUE THREAD

**Issue by atrudeau-vitall** [srmeyers/git-prefix#29]
**Background** 
Using a VSCode workspace you can add and work on multiple repositories, each repository you add to a workspace also has its own collapsable section in the source control panel.

**Steps to reproduce**
1. Create a workspace with 2 or more repositories in VSCode
2. Install + configure the git prefix extension
3. Click the git prefix button in either repo's source control section

**Expected output**
The commit message box for the selected repo is prefixed with the extension's prefix message, and each source control section's "collapsed" state is unaffected by clicking the git prefix button.

**Actual Output**
The commit prefix is set correctly, however the source control section for the _first_ repo in the workspace toggles (if it was open, it is now closed, vice versa) regardless of which git prefix button was clicked.

---

**Environment**
VSCode Version: 1.86.0 (Universal)
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin x64 21.6.0

**Comment by johannes-schmitt** [comment]
I'm experiencing the same issue. In my case it's not a workspace with multiple repositories but a git repository that contains git submodules. I assume it's the same root cause, as the _Source Control_ panel shows multiple repositories.

**Comment by dunnmj42** [comment]
I'm also experiencing this and have been for some time.

**Comment by sr-tream** [comment]
The reason is [here](https://github.com/srmeyers/git-prefix/blob/main/src/extension.ts#L44). I think the author tried to set focus on input box, but instead of this, focus sets on repository widget and next **select** action collapse it.

**Comment by campbell-brown** [comment]
When can we expect a release with this fix?

**Comment by Spenhouet** [comment]
> When can we expect a release with this fix?

It is already released. The bug should already be fixed when you do an update of the extension.

**Comment by campbell-brown** [comment]
> It is already released. The bug should already be fixed when you do an update of the extension.

I have the latest version and still have the issue.

## Versions

Extension version
```
Identifier srmeyers.git-prefix
Version 1.3.3
Last Updated 2025-07-10, 12:59:49
```

VS Code version

```
Version: 1.102.0 (user setup)
Commit: cb0c47c0cfaad0757385834bd89d410c78a856c0
Date: 2025-07-09T22:10:34.600Z
Electron: 35.6.0
ElectronBuildId: 11847422
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Windows_NT x64 10.0.19045
```
## Steps to reproduce
Set up example repository with a submodule
```
$ mkdir git-prefix-test
$ cd git-prefix-test
$ git init
$ git submodule add https://github.com/octocat/Hello-World.git
$ code .
```
Configure extension:
```
    "gitPrefix.pattern": ".*",
    "gitPrefix.replacement": "TEST",
```
Clicking here:

<img width="389" height="285" alt="Image" src="https://github.com/user-attachments/assets/ba8eca78-627d-4f45-a52e-7f3d92edc258" />

Collapses the main repository:

<img width="393" height="170" alt="Image" src="https://github.com/user-attachments/assets/15dec3d3-4d0e-4601-b54c-d2afe7785e67" />

I think this is the latest version of the extension, according to the changelog. Do I misunderstand the issue and have found another one? Or am I doing something not quite right?

**Comment by dunnmj42** [comment]
I'm also on the most recent version and this is still happening for me FWIW
